name: black
on: pull_request
jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin '${{ github.base_ref }}' --depth=1
      - run: |
          python -m pip install --upgrade pip
          python -m pip install black==23.3
      - run: |
          git diff 'origin/${{ github.base_ref }}' --name-only -- '*.py' \
            | xargs black --check --diff --verbose --extend-exclude third_party
