name: Check
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  check_suite:
    types: [requested, rerequested]

jobs:
  run:
    name: Check
    runs-on: "ubuntu-20.04"
    steps:
    - name: Help
      run: |
        echo Checked
